osx_image: xcode8.4 # define OS X image which will be mounted

dist: trusty # use Ubuntu Trusty for Linux operation system

# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

# Define Node.js as the programming language as we have a web application
language: node_js
node_js: '12'

addons:
  chrome: stable # Install chrome stable on operating systems

services:
  - xvfb

addons:
  apt:
    packages:
      - xvfb

# A list of operating systems which are used for tests
os:
  - linux
  - osx

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install --no-progress

script:
  - npm test

notifications:
  slack: riceeclipse:HVcYx7InaxdEFzQHaatd1UiH
